### PR TITLE
add geo event attributes

### PR DESCRIPTION
**Pull request by 1000i100**
#112 basic addition with test but not deep test geo is a string no controls it's 2 float separated by semicolon

### CODE REVIEW

**Comment by 1000i100** [comment]
To merge, i suggest to stop at 3b522fc

**Comment by evelynhathaway** [comment]
@sebbo2002 Would you like some help creating pull requests from cherrypicking or rebasing from this branch?

From my understanding, the following are two feature branches and the ones that will not be merged.

<details> 
<summary>PR: GEO position event property</summary>

- 786a377 better controls on geo attributes
- 3b522fc geo attribute documentation
- 7a6326e GEO: is include in generated .ics file
- 1bb397c GEO: is include in generated .ics file with no escaped semicolon
- a023548 escape anything, don't fail when it's not a string.
- Add a new commit with the types for this new feature

</details>

<details> 
<summary>PR: ICalTools.formatDate should not modify UTC</summary>

- 14f3f0a FIX #99

</details>

<details> 
<summary>Not included in any PR</summary>

- f6dc1ee add build step in postinstall to enable git npm inclusion
- 4ddd72a add built dist for personal use since merge. (DO NOT MERGE THIS)
- a124165 no more auto-build because npm fail to build without dev dependencies… (DO NOT MERGE THIS)
- 975029c update built dist for personal use since merge. (DO NOT MERGE THIS)
- adbb9e3 update built dist for personal use since merge. (DO NOT MERGE THIS)
- fe7bf91 update built dist for personal use since merge. (DO NOT MERGE THIS)
- 1a4889e update built dist for personal use since merge. (DO NOT MERGE THIS)

</details>

**Comment by sebbo2002** [comment]
@evelynhathaway Sorry for the delay, there's a lot to do right now. If you want to help, I would be very happy. I'm not getting around to it right now.

**Comment by sebbo2002** [comment]
Close PR as `geo` is already included…

**Pull request closed without merging**
