### PR TITLE
Add htmlDescription as an attribute in events

### PR DESCRIPTION
**Pull request by alFReD-NSH**

### CODE REVIEW

**Comment by AndrewLane** [comment]
Without this change, you have to call the function to get htmlDescription to work, right?

**Comment by sebbo2002** [comment]
You're right, this is required for loading/saving the JSON…

**Comment by sebbo2002** [comment]
I just published a new version on npm.
Sorry for let you waiting so long…

**Comment by AndrewLane** [comment]
@sebbo2002 thanks!!!!

**Pull request merged**
