### PR TITLE
Allow iCal extensions to be selectively disabled

### PR DESCRIPTION
**Pull request by mdeltito**
This adds a new constructor property which allows the user to configure which iCal extensions are enabled. All currently-used extension fields are enabled by default. This allows for selective disabling of extensions, which may be necessary depending on the use-case and which calendar providers are being targeted.

### CODE REVIEW

**Comment by sebbo2002** [comment]
Sorry if I misunderstand something, but when is it necessary to disable these extensions? As far as I know client implementations are required to ignore unknown attributes of the calendar.

**Comment by mdeltito** [comment]
`X-WR-CALNAME` has caused issues in Outlook where a feed referencing a single event is forced into a new calendar, rather than added to the default calendar. Google Calendar and macOS Calendar both require the user to select the target calendar when importing, but we've heard feedback that this is not always the case for Outlook. Removing this extension resolves the issue.

Definitely open to there being a better/different solution to this problem!

**Comment by sebbo2002** [comment]
Since this is not a problem of `ical-generator` but rather a bug in Outlook, I would not want to merge this pull request at this time. However, I release it for voting. If there are enough people who need the feature, I would merge it.

**Comment by mdeltito** [comment]
@sebbo2002 I don't think it's necessarily a bug in Outlook - from [their spec](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcical/1da58449-b97e-46bd-b018-a1ce576f3e6d):

> This property MUST be omitted if the iCalendar represents a single appointment or meeting.

Given that, I'd argue that `ical-generator` should be matching this behavior but... there's no way be sure with these extensions (afaik) that all providers have implemented them the same. In fact, we're seeing that with this extension in particular all providers have NOT implemented it the same. That's why I've taken the approach here of providing a way to disable extensions.

**Comment by sebbo2002** [comment]
Since this pull request has received very little approval so far, and is also no longer compatible, I would now close this PR for the time being. I hope this is okay for all involved.

**Pull request closed without merging**
