### PR TITLE
add support for the iCalendar fields "CREATED" and "LAST-MODIFIED"

### PR DESCRIPTION
**Pull request by sweber83**
This adds the fields `CREATED` and `LAST-MODIFIED` to events.

### CODE REVIEW

**Comment by antoinerousseau** [comment]
Hi guys,
I realize that when I'm feeding my output to Google Calendar, if some events are modified, Google does not take the modifications into account. I think that when the UID does not change, and the event has no "modified" date, it ignores the content.
Thus, what's up with this PR? Can I help? :)
Cheers,
Antoine

**Comment by sebbo2002** [comment]
> Edit: I realize it's part of the 3.0 roadmap \o/

Yep, it is. Feel free update this pull request (or create a new one) to build this feature for the 3.0 version. It's already in develop.

**Comment by antoinerousseau** [comment]
OK! Also, I'm wondering if maybe I should increment the `SEQUENCE` when updating events.
https://tools.ietf.org/html/rfc5546#section-4.2.3

**Comment by sebbo2002** [comment]
You can do so, see [the docs](https://github.com/sebbo2002/ical-generator#sequencenumber-sequence). But I don't know if that's enough for Google Calendar as I don't use it…

**Comment by sebbo2002** [comment]
There is a more up-to-date PR available: #75 
Close it for now…

**Pull request closed without merging**
