### PR TITLE
Use UUID v4 for the ID property and remove the `domain` property

### LINKED ISSUE #203: Use UUIDs for Event UIDs
As discussed in #200, according to  https://icalendar.org/New-Properties-for-iCalendar-RFC-7986/5-3-uid-property.html, the UID property should preferably be a UUID and should not include any domain information. This will also make the domain attribute obsolete.

### PR DESCRIPTION
**Pull request by gprst**
Resolves #203.

- UUID v4 support: I chose [uuid-random](https://www.npmjs.com/package/uuid-random) over more popular packages (such as [uuid](https://www.npmjs.com/package/uuid)) because its unpacked size is much smaller, and it only implements the feature we need here — random (cryptographically secure) UUID v4 generation.

- `domain` property removal: as this property isn't used anywhere anymore, it is completely wiped from the project.

With this, the UID property of an event is now a UUID, rather than an ID with `@somedomain` appended.

### CODE REVIEW

**Comment by gprst** [comment]
Hi, out of curiosity, is there any preliminary thing I'd need to fulfil before this PR gets merged ?

**Comment by sebbo2002** [comment]
@gprst No, this PR is currently lying around until several breaking changes for a new major version have come together. I don't see this PR as so important that it should be merged immediately. So it's not for you to do, don't worry. ☺️

**Comment by gprst** [comment]
@sebbo2002 It appears you've just taken my commits and published them in your name. That's not nice, but I don't mind.

**Comment by sebbo2002** [comment]
@gprst Fortunately, it only looks like this at first glance.

Unfortunately, the pull request could no longer be merged without major conflicts after the [typescript refactoring](https://github.com/sebbo2002/ical-generator/commit/5053d21a0d5f15e3b3926904936ff75a96d933b7), so I decided to go [this](https://github.com/sebbo2002/ical-generator/commit/a4c19ccdba037e7196b47bb571c26f2e6068f538) route. 

Of course, I could have written to you again to update the PR, but honestly: I assumed that no one would feel offended, because in the end there was only one `import` and one `uuid()` left from your pull request, as the removal of `domain()` was done for other reasons during the typescript refactoring without having your pull request in mind. Feed free to double check the commits, I linked them above.

Of course, you are free to open a pull request and comment on the use of `uuid-random`, so you are welcome to point out that this piece of code originally came from you. But if you do, it's please also link to this issue, because I don't want to be accused of stealing code.

**Comment by gprst** [comment]
Okay, thank you for taking the time to explain me what lead to this PR to be closed and the feature still be added. I should have taken the time to look at the differences between the code you wrote and mine. My appologies for the quick accusations.

**Pull request closed without merging**
