### PR TITLE
Added support for transparency property of event

### PR DESCRIPTION
**Pull request by SebastiaandenBoer**
Adds support for the transparency property of an event, used by online calendar applications to determine whether or not the scheduled event is final or not.

@sebbo2002 Would you consider merging this?

### CODE REVIEW

**Comment by madmod** [comment]
I think that in order to follow the convention already in place where ical property names are converted into something more human friendly the option should be called `transparency` instead of `transp`. This is also closer to the heading `Time Transparency` in [Section 4.8.2.7](https://tools.ietf.org/html/rfc2445#section-4.8.2.7).

**Comment by SebastiaandenBoer** [comment]
@sebbo2002 BTW, do you have a timeline for future feature additions? It would be highly appreciated.

**Comment by sebbo2002** [comment]
@SebastiaandenBoer  As I currently have a lot to do with work and my bachelor thesis, I unfortunately have to negate.

**Comment by SebastiaandenBoer** [comment]
@sebbo2002 Good luck on the bachelor thesis!

P.S. Actually, I just finished mine recently and now it's up to you to defend the reputation of our (more or less similar) first name ;)

**Comment by sebbo2002** [comment]
I just published a new version on npm.
Sorry for let you waiting so long…

**Pull request merged**
