### PR TITLE
ICalLuxonDateTimeStub Issues on types

### PR DESCRIPTION
**Pull request by alfonsodav**
74// get isValid(): boolean
Type invalid, produces compilation error

### About this Pull Request
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
    - …
- **What is the current behavior?** (You can also link to an open issue here)
    - …
- **What is the new behavior (if this is a feature change)?**
    - …
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
    - …
- **Other information**:
    - …

### Pull Request Checklist

- [x] My code follows the code style of this project
    - Run `npm run lint` to double check
- [ ] My change requires a change to the documentation
    - [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
    - Run `npm run test` to run the unit tests and `npm run coverage` to generate a coverage report
- [ ] All new and existing tests passed
- [ ] My commit messages follow the [commit guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit)

### CODE REVIEW

**Comment by sebbo2002** [comment]
Luxon's `isValid` is clearly a getter, if I compare that with [the Typescript types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/luxon/src/datetime.d.ts#L781) or [the documentation](https://moment.github.io/luxon/api-docs/index.html#datetimeisvalid). So this should work so far. Could you post a small example here so I can understand your compilation  error?

**Comment by alfonsodav** [comment]
Hello, it happens when I try to compile in a project with adonisJS, node version 16, the error indicates that this get cannot be in that place because it is a type, you are inside an interface and it produces a syntax error

`[ error ]  typescript compiler errors
node_modules/ical-generator/dist/types.d.ts:67:5 - error TS1131: Property or signature expected.

67     get isValid(): boolean;
       ~~~
node_modules/ical-generator/dist/types.d.ts:67:9 - error TS1005: ';' expected.

67     get isValid(): boolean;
           ~~~~~~~
node_modules/ical-generator/dist/types.d.ts:67:18 - error TS1005: ';' expected.

67     get isValid(): boolean;
                    ~
node_modules/ical-generator/dist/types.d.ts:68:13 - error TS1005: ';' expected.

68     toJSON(): string;
               ~
node_modules/ical-generator/dist/types.d.ts:69:1 - error TS1128: Declaration or statement expected.

69 }
   ~`

**Comment by alfonsodav** [comment]
test https://drive.google.com/file/d/1EheJHyhig1UX7a3syZjTBasNQ7YZXKS5/view?usp=sharing

**Comment by sebbo2002** [comment]
Unfortunately, I don't know what to do with the screenshot. Can you reproduce the problem in a minimal example? Because when I use the library with luxon, it seems to work. Which versions of `ical-generator`, `luxon` and `@types/luxon` are you using?


Bildschirmfoto 2022-08-12 um 14 36 40

**Comment by alfonsodav** [comment]
I apologize for the inconvenience, thank you very much, the problem is caused by using a version of typescript that did not support that expression

**Pull request closed without merging**
