### PR TITLE
Added bySetPos support for repeating events

### PR DESCRIPTION
**Pull request by farhadSagar**
Added support for repeating bySetPos (integer, must be used with byDay).

Must include byDay when used with bySetPos. Will use the first element of the byDay array (if sent multiple values) when bySetPos is present.

Added test coverage for the changes. Updated readme documentation.

### CODE REVIEW

**Comment by farhadSagar** [comment]
any update???

**Comment by sebbo2002** [comment]
Sorry, found no time to review it yet. Hope to do this on Saturday. Sorry for that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sebbo2002** [comment]
Merged it, thanks for your PR. Will publish a new version this afternoon.

**Pull request merged**
