### PR TITLE
remove moment.js from quickstart example

### PR DESCRIPTION
**Pull request by bkleinen**
This pull request changes the quickstart example in the README not to use moment.js anymore. 
Example is also added in the examples folder.

### CODE REVIEW

**Comment by sebbo2002** [comment]
moment.js is a supported library, so the code is not invalid or anything? Why do you want to remove moment.js here? I assume any JavaScript developer manages to apply the QuickStart example to other Date objects (native, Date.js, etc.).

**Comment by bkleinen** [comment]
Even as a non-JavaScript-Developer I managed to make the quickstart run and later, after I realized that the used moment.js library is not a good choice anymore change it to date.js - but it was some hassle, I needed to read aabout node modules and the different imports, and finally quite frustrating to
realize that the moment.js Library I started to read about because it was used in the example was not a  good choice anymore. Thus my suggestion to use an example for "Quick Start" that runs out of the box and without the need to download another node module.

**Comment by sebbo2002** [comment]
From that perspective, it makes total sense, thanks for the explanation.

**Pull request merged**
