### PR TITLE
add created and last-modified event field

### PR DESCRIPTION
**Pull request by antoinerousseau**
This updates #71

### CODE REVIEW

**Comment by sebbo2002** [comment]
Thanks for your work. As I currently try to update ical-generator to use [moment.js](https://momentjs.com/) internally, I want to reflect these changes in your added methods as well. Feel free to do these changes yourself if you have time, otherwise I'll do that when I have some spare time. Great work!


### Todo notes

- [ ] use moment.js internally (utc only, see [Event::start()](https://github.com/sebbo2002/ical-generator/blob/develop/src/event.js#L136))

**Comment by antoinerousseau** [comment]
Yep, using moment would be better, but it should be done in a latter PR so I think you can merge this one first and open a new one for moment.js

**Comment by sebbo2002** [comment]
Why is that? What is the advantage? The PR cannot be released immediately either way, because the other tasks on the 3.0 list have to be processed first.

**Comment by antoinerousseau** [comment]
I'm not sure why other tasks have to come first but I'm happy to help, let me know what I can do? Implement Moment.js? Throw Errors? Maybe you can focus on the CI and tests?

**Comment by sebbo2002** [comment]
Other topics should not be preferred. I'd just like to make changes to match the new programming style. So it would be great if you would fix moment.js for your pull request, then I can merge it directly.

If you have the impression that little is happening at the moment. You're absolutely right. Due to my bachelor thesis, which I'm currently writing, I don't have enough time to deal with this project in parallel.

**Comment by antoinerousseau** [comment]
No worries, I completely understand!
Like most of the people in the open-source world I think :)

**Comment by antoinerousseau** [comment]
PR updated

**Comment by sebbo2002** [comment]
Nice work, thank you! 🙌🏼

**Pull request merged**
