### PR TITLE
Support VTimezone

### LINKED ISSUE #122: Include VTimezone
I would love to see `VTIMEZONE` included in the ical-generator. Some calendars are fine without them, like iCal, and Google, however Outlook requires a `VTIMEZONE` section when a timezone is used, otherwise it won't parse. I imagine there are other calendars that are also sticklers as well.

I imagine this could work by bundling in the [information from here](https://github.com/libical/libical/tree/master/zoneinfo), possibly as a build step, then include it in the ics file when relevant.

### PR DESCRIPTION
**Pull request by Gr8z**
Fixes #122

### CODE REVIEW

**Comment by sebbo2002** [comment]
**Current status of the pull request:**
- [x] Implementation
- [ ] Unit Tests
- [ ] Documentation

**Comment by Gr8z** [comment]
Never worked with Tests before, can someone give a hand?

**Comment by sebbo2002** [comment]
Have a look at the tests that already exist, e.g. those from [this pull request here](https://github.com/sebbo2002/ical-generator/pull/89/files). If you have any questions, feel free to add a comment.

But please don't take this as a work assignment, if you don't feel like it, that's fine. ☺️

**Comment by mfbx9da4** [comment]
This looks really great! Great work 👍🙏

**Pull request closed without merging**
